### PR TITLE
judge example exercises as integration tests

### PR DESCRIPTION
**Pull request by ninewise**

### CODE REVIEW

**Comment by ninewise** [comment]
Oh hmmm, the java.lang Stacktrace line differs between my computer and the dockerfile version...

**Comment by ninewise** [comment]
I'm modifying the script to not compare line numbers in stack traces.

**Comment by thepieterdc** [comment]
@ninewise if it's possible, I would simply check the first line of the output trace, this should exclude any JDK internals.

**Comment by ninewise** [comment]
Since apparently even the location of the files differs (in modules versus not in modules), just scratching all ` at ...(...)` lines seems best.

**Pull request merged**
