### PR TITLE
improve method finding for generic methods

### PR DESCRIPTION
**Pull request by ninewise**
- [x] Use for constructors, too? Requires new stub though.
- [x] Many 'not yet implemented': can these occur? Implement them anyway.

### CODE REVIEW

**Comment by ninewise** [comment]
This seems impossible for constructors since we don't have the actual types, only objects (so Class, not Type). We might not be able to find (slightly wrong) constructors we *could* use, but we'll still find all correct constructors as before.

**Comment by ninewise** [comment]
I think this is now finished for normal methods.

It's not implemented for constructors, yet: I can't dynamically find the `Type`s given a call to current `AssertionStubber.stub` method since generic types of Objects are erased at runtime. Possible solution: if a stubbed interface has a `void _construct(...)` method, I can take the `Type`'s of that one to find the actual constructor. Better ideas?

**Comment by ninewise** [comment]
> Some the messages explaining the type issues will not be understood by people starting out with Java. I don't have any ideas immediately on how to fix this, but I'm pretty sure it will be a problem.

The messages in [the Assignable class](https://github.com/dodona-edu/judge-java12/pull/38/files#diff-5a007a495217bb117dc9c46b0cf669c2) won't ever be shown to the user. I included them to simplify debugging and left them because they won't impact performance. Are the other messages unclear, too?

> Also since this judge has i18n support now, any chance we can translate this?

I will translate all messages shown to the user before merging this.

**Comment by charvp** [comment]
No, that's fine then.

**Pull request merged**
